### ISSUE TITLE
Error in log since 0.8.1

### ISSUE THREAD

**Issue by spudje** [crowbarz/ha-pioneer_async#26] opened 2023-04-10 20:42 UTC
Just updated to 0.8.1 from pre 0.8 and found this error in my log.

`>> PioneerAVR._connection_listener() exception: string index out of range`

Integration does stll seem to work though. So no clue what is wrong.
Using with a VSX-922.

**Comment by 11harveyj** [comment] 2023-04-10 20:52
This is probably coming from the response for the ?AST and ?VST commands. We've got mixed documentation for those commands, but we need them, especially AST so that we can tell if the input source is in multi channel mode or not, which in turn is used to determine what sound modes are returned in HA. 

Are you able to run in debug mode and upload the logs so I can confirm?

**Comment by DachnikGarik** [comment] 2023-04-15 18:39
Invalid config for [media_player.pioneer_async]: expected a dictionary for dictionary value @ data['debug_config']. Got None. (See ?, line ?).
I have this problem too. I can't run the plugin in debug mode because of the warning from HA about incorrect config.

**Comment by 11harveyj** [comment] 2023-04-15 18:43
@DachnikGarik what model AVR do you have?

**Comment by D-Jeffrey** [comment] 2023-04-16 02:26
@DachnikGarik Confirming that you do not have any lines in your `configuration.yaml`

I think the @spudje issue is related to #13 it could be the VSX-922 give a short answer too.  We the results of the `?AST` and `?VST` query commands to see how many bits are in the answer.  Maybe there is less than 33 or more than 33 but less than 43.  related to `aiopioneer/parsers/information.py`

**Comment by crowbarz** [comment] 2023-04-16 20:19
@DachnikGarik there was an incorrect default value in 0.8.1 that caused that error  if `debug_config` was not defined in the YAML configuration. This is now fixed in 0.8.2.

(It also means that you are configuring the integration using `configuration.yaml` rather than via the UI, the latter is preferred and is better tested.)

**Comment by DachnikGarik** [comment] 2023-04-16 20:39
> @DachnikGarik what model AVR do you have?

VSX-828

**Comment by 11harveyj** [comment] 2023-04-16 21:26
@spudje @DachnikGarik I need your both of your log files (or pull the aiopioneer package from [GH ](https://github.com/crowbarz/aiopioneer) and run `test-avr.py -h <IP address>`) to confirm where this error is coming from.

With the VSX-828, I have no documentation for at all from Pioneer, so not even sure what's compatible or not via its serial interface.

Saying this though, I think I might have spotted where the error is, at least for the VSX-922 / FY13 AVRs

**Comment by D-Jeffrey** [comment] 2023-04-18 01:55
It is a 2013 model so I would suggest it has the short response issue.
https://www.hifiengine.com/manual_library/pioneer/vsx-828.shtml 

@11harveyj  There is no `test-avr.py` in that repo?  I think you mean `python3 test_api.py -h <theipaddress>`

This assumes you have Python installed, if not then see https://github.com/PackeTsar/Install-Python#readme and you can download the package as a zip file https://github.com/crowbarz/aiopioneer/archive/refs/heads/dev.zip onto your computer.

**Comment by 11harveyj** [comment] 2023-04-18 05:52
> @11harveyj There is no `test-avr.py` in that repo? I think you mean `python3 test_api.py -h <theipaddress>`

Yes, was tired when I sent the last reply, sorry. Will update

**Comment by crowbarz** [comment] 2023-05-21 18:59
I've overhauled the `aiopioneer` logging since this bug was created. Please enable debug level logging for the `aiopioneer` namespaces in the `logger` HA integration, and include the relevant log entries (direct from `homeassistant.log` or from the full log, not via the UI as it unhelpfully coalesces similar log entries) if the exceptions are still occurring. The logs should now show the command that was sent immediately prior to the exception.

**Closed** 2024-01-14 19:03 UTC
